
-- Script basico para crear un nuevo usuario/esquema

CREATE USER $DB_USER IDENTIFIED BY $DB_PASSWORD;
GRANT CREATE SESSION TO $DB_USER;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO $DB_USER;
ALTER USER $DB_USER QUOTA UNLIMITED ON USERS;