services:
  oracle-db:
    image: gvenzl/oracle-free:23-slim-faststart
    container_name: oracle-db
    environment:
      ORACLE_PASSWORD:    ${ORACLE_PASSWORD:?ORACLE_PASSWORD no definido}
      APP_USER:           ${DB_USER:?DB_USER no definido}
      APP_USER_PASSWORD:  ${DB_PASSWORD:?DB_PASSWORD no definido}
    ports:
      - "${DB_PORT:-1521}:1521"
    volumes:
      - ./Backend/DB/init-oracle.sql:/container-entrypoint-initdb.d/init-oracle.sql
      - oracle_data:/opt/oracle/oradata
    networks:
      - movies-network
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  movies-api:
    build:
      context: ./Backend/API
      dockerfile: Dockerfile
    command: ["pnpm", "run", "dev"]
    container_name: movies-api
    depends_on:
      oracle-db:
        condition: service_healthy
    environment:
      DB_USER:              ${DB_USER:?DB_USER no definido}
      DB_PASSWORD:          ${DB_PASSWORD:?DB_PASSWORD no definido}
      DB_CONNECTION_STRING: ${DB_CONNECTION_STRING:-oracle-db:1521/FREEPDB1}
    ports:
      - "${API_PORT:-3001}:3001"
    volumes:
      - ./Backend/API/src:/app/src
    networks:
      - movies-network
    restart: on-failure

volumes:
  oracle_data:
    driver: local

networks:
  movies-network:
    driver: bridge